line-length = 88
target-version = "py313"

[lint]
select = ["ALL"]
ignore = [
    "D203",
    "D213",
    "Q000",
    "Q003",
    "COM812",
    "TC003",
]

[lint.extend-per-file-ignores]
# https://github.com/astral-sh/ruff/issues/4368#issuecomment-2245567481
"tests/**/*.py" = [
    # at least this three should be fine in tests:
    "S101", # asserts allowed in tests...
    "ARG", # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT", # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    # The below are debateable
    "PLR2004", # Magic value used in comparison, ...
    "S311", # Standard pseudo-random generators are not suitable for cryptographic purposes
    "INP001", # https://github.com/astral-sh/ruff/issues/6474
    "D103", # Tests can self document
    "D104", # Not relevant for tests
    "S602", # Test env is controlled
    "S603", # Test env is controlled
    "S607", # Test env is controlled
]

[format]
quote-style = "single"
